apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  selector:
    app: demo-app
  ports:
    - name: http
      protocol: TCP
      port: 8083 # service port
      targetPort: 80 # container port
